classDiagram
    Library "1" o-- "*" Book
    Library "1" o-- "*" User
    Library "1" *-- "*" Loan
    Loan "*" --> "1" Book
    Loan "*" --> "1" User

    class Library {
        add_book()
        register_user()
        create_loan()
    }
    class Book {
        title: str
        author: str
        state: bool
        mark_as_available()
        mark_as_unavailable()
    }
    class User {
        name: str
        email: str
    }
    class Loan {
        start_date: str
        end_date: str
        close_loan()
    }
